/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.dftech.screens;

import br.com.dftech.dal.Moduloconexao;
import java.text.DateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import java.sql.*;
import java.io.File;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author dario
 */
public class TelaPrincipal extends javax.swing.JFrame {

    Connection conexao = null;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        // Maximiza a janela automaticamente para excelente visualização em notebooks (16", 15.6", etc.)
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        // Ícone da janela
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/br/com/dftech/icons/x.png")).getImage());
        conexao = Moduloconexao.conector();
        // Relógio digital dinâmico que atualiza a data e hora a cada segundo
        new javax.swing.Timer(1000, new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                java.util.Date data = new java.util.Date();
                java.text.SimpleDateFormat fData = new java.text.SimpleDateFormat("dd/MM/yyyy");
                java.text.SimpleDateFormat fHora = new java.text.SimpleDateFormat("HH:mm:ss");
                lblData.setText("<html>Data: " + fData.format(data) + "<br>Hora: " + fHora.format(data) + "</html>");
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        desktop = new javax.swing.JDesktopPane();
        lblUsuario = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel() {
            private java.awt.Image image = null;
            private java.awt.image.BufferedImage cachedScaledImage = null;
            private int cachedW = -1;
            private int cachedH = -1;

            @Override
            public void setIcon(javax.swing.Icon icon) {
                super.setIcon(icon);
                if (icon instanceof javax.swing.ImageIcon) {
                    this.image = ((javax.swing.ImageIcon) icon).getImage();
                    this.cachedScaledImage = null;
                } else {
                    this.image = null;
                    this.cachedScaledImage = null;
                }
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                if (image != null) {
                    int width = getWidth();
                    int height = getHeight();
                    if (width > 0 && height > 0) {
                        int imgW = image.getWidth(this);
                        int imgH = image.getHeight(this);
                        if (imgW > 0 && imgH > 0) {
                            double ratio = Math.min((double) width / imgW, (double) height / imgH);
                            int newW = Math.max(1, (int) (imgW * ratio));
                            int newH = Math.max(1, (int) (imgH * ratio));
                            int x = (width - newW) / 2;
                            int y = (height - newH) / 2;

                            if (cachedScaledImage == null || cachedW != newW || cachedH != newH) {
                                cachedW = newW;
                                cachedH = newH;
                                cachedScaledImage = renderSharpImage(image, newW, newH);
                            }

                            if (cachedScaledImage != null) {
                                java.awt.Graphics2D g2d = (java.awt.Graphics2D) g.create();
                                g2d.setRenderingHint(java.awt.RenderingHints.KEY_INTERPOLATION, java.awt.RenderingHints.VALUE_INTERPOLATION_BICUBIC);
                                g2d.setRenderingHint(java.awt.RenderingHints.KEY_RENDERING, java.awt.RenderingHints.VALUE_RENDER_QUALITY);
                                g2d.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                                g2d.drawImage(cachedScaledImage, x, y, this);
                                g2d.dispose();
                                return;
                            }
                        }
                    }
                }
                super.paintComponent(g);
            }

            private java.awt.image.BufferedImage renderSharpImage(java.awt.Image srcImg, int targetW, int targetH) {
                int w = srcImg.getWidth(null);
                int h = srcImg.getHeight(null);
                if (w <= 0 || h <= 0) return null;

                java.awt.image.BufferedImage current = new java.awt.image.BufferedImage(w, h, java.awt.image.BufferedImage.TYPE_INT_ARGB);
                java.awt.Graphics2D gInitial = current.createGraphics();
                gInitial.setRenderingHint(java.awt.RenderingHints.KEY_INTERPOLATION, java.awt.RenderingHints.VALUE_INTERPOLATION_BICUBIC);
                gInitial.setRenderingHint(java.awt.RenderingHints.KEY_RENDERING, java.awt.RenderingHints.VALUE_RENDER_QUALITY);
                gInitial.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                gInitial.drawImage(srcImg, 0, 0, null);
                gInitial.dispose();

                // Multi-pass scaling for crystal clear sharpness
                do {
                    if (w > targetW) {
                        w /= 2;
                        if (w < targetW) w = targetW;
                    } else {
                        w = targetW;
                    }

                    if (h > targetH) {
                        h /= 2;
                        if (h < targetH) h = targetH;
                    } else {
                        h = targetH;
                    }

                    java.awt.image.BufferedImage next = new java.awt.image.BufferedImage(w, h, java.awt.image.BufferedImage.TYPE_INT_ARGB);
                    java.awt.Graphics2D g2 = next.createGraphics();
                    g2.setRenderingHint(java.awt.RenderingHints.KEY_INTERPOLATION, java.awt.RenderingHints.VALUE_INTERPOLATION_BICUBIC);
                    g2.setRenderingHint(java.awt.RenderingHints.KEY_RENDERING, java.awt.RenderingHints.VALUE_RENDER_QUALITY);
                    g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                    g2.setRenderingHint(java.awt.RenderingHints.KEY_ALPHA_INTERPOLATION, java.awt.RenderingHints.VALUE_ALPHA_INTERPOLATION_QUALITY);
                    g2.setRenderingHint(java.awt.RenderingHints.KEY_COLOR_RENDERING, java.awt.RenderingHints.VALUE_COLOR_RENDER_QUALITY);
                    g2.drawImage(current, 0, 0, w, h, null);
                    g2.dispose();

                    current = next;
                } while (w != targetW || h != targetH);

                return current;
            }
        };
        Menu = new javax.swing.JMenuBar();
        menCadUse = new javax.swing.JMenu();
        menCadCli = new javax.swing.JMenuItem();
        menCadOS = new javax.swing.JMenuItem();
        menCadUsu = new javax.swing.JMenuItem();
        menCadPeca = new javax.swing.JMenuItem();
        menRel = new javax.swing.JMenu();
        menRelCli = new javax.swing.JMenuItem();
        menRelSer = new javax.swing.JMenuItem();
        menRelPecas = new javax.swing.JMenuItem();
        menRelOS = new javax.swing.JMenuItem();
        menAju = new javax.swing.JMenu();
        menAjuSob = new javax.swing.JMenuItem();
        menOpc = new javax.swing.JMenu();
        menOpcSai = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dftech - Sistema para controle de OS");
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(935, 551));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        desktop.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent evt) {
                for (javax.swing.JInternalFrame f : desktop.getAllFrames()) {
                    if (f.isVisible() && !f.isMaximum()) {
                        centralizarFrame(f);
                    }
                }
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblUsuario.setText("Usuário");

        lblData.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblData.setText("Data");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/dftech/icons/x.png"))); // NOI18N

        menCadUse.setText("Cadastro");
        menCadUse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadUseActionPerformed(evt);
            }
        });

        menCadCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menCadCli.setText("Cliente");
        menCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadCliActionPerformed(evt);
            }
        });
        menCadUse.add(menCadCli);

        menCadOS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menCadOS.setText("OS");
        menCadOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadOSActionPerformed(evt);
            }
        });
        menCadUse.add(menCadOS);

        menCadUsu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menCadUsu.setText("Usuários");
        menCadUsu.setEnabled(false);
        menCadUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadUsuActionPerformed(evt);
            }
        });
        menCadUse.add(menCadUsu);

        menCadPeca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menCadPeca.setText("Peça");
        menCadPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadPecaActionPerformed(evt);
            }
        });
        menCadUse.add(menCadPeca);

        Menu.add(menCadUse);

        menRel.setText("Relatório");
        menRel.setEnabled(false);
        menRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelActionPerformed(evt);
            }
        });

        menRelCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menRelCli.setText("Clientes");
        menRelCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelCliActionPerformed(evt);
            }
        });
        menRel.add(menRelCli);

        menRelSer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menRelSer.setText("Serviços");
        menRelSer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelSerActionPerformed(evt);
            }
        });
        menRel.add(menRelSer);

        menRelPecas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menRelPecas.setText("Peças em Estoque");
        menRelPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelPecasActionPerformed(evt);
            }
        });
        menRel.add(menRelPecas);

        menRelOS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menRelOS.setText("OS por Cliente");
        menRelOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelOSActionPerformed(evt);
            }
        });
        menRel.add(menRelOS);

        Menu.add(menRel);

        menAju.setText("Ajuda");
        menAju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menAjuActionPerformed(evt);
            }
        });

        menAjuSob.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menAjuSob.setText("Sobre");
        menAjuSob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menAjuSobActionPerformed(evt);
            }
        });
        menAju.add(menAjuSob);

        Menu.add(menAju);

        menOpc.setText("Opções");

        menOpcSai.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menOpcSai.setText("Sair");
        menOpcSai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menOpcSaiActionPerformed(evt);
            }
        });
        menOpc.add(menOpcSai);

        Menu.add(menOpc);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario)
                    .addComponent(lblData)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                .addContainerGap(25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblUsuario)
                        .addGap(30, 30, 30)
                        .addComponent(lblData)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1150, 680));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void centralizarInternalFrame(javax.swing.JInternalFrame frame) {
        desktop.add(frame);
        frame.setVisible(true);
        try {
            frame.setMaximizable(true);
            frame.setMaximum(true);
            frame.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
            // ignore
        }
        centralizarFrame(frame);
    }

    private void centralizarFrame(javax.swing.JInternalFrame frame) {
        if (frame != null && frame.isVisible() && !frame.isMaximum()) {
            int desktopWidth = desktop.getWidth();
            int desktopHeight = desktop.getHeight();
            int frameWidth = frame.getWidth();
            int frameHeight = frame.getHeight();
            if (desktopWidth > 0 && desktopHeight > 0) {
                int x = Math.max(0, (desktopWidth - frameWidth) / 2);
                int y = Math.max(0, (desktopHeight - frameHeight) / 2);
                frame.setLocation(x, y);
            }
        }
    }

    private void menCadOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadOSActionPerformed
        TelaOS os = new TelaOS();
        centralizarInternalFrame(os);
        TelaOS.txtCliPesquisar.requestFocus();

    }//GEN-LAST:event_menCadOSActionPerformed

    private void menRelSerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelSerActionPerformed
        // Criar painel com campos de data formatados (máscara dd/MM/yyyy)
        javax.swing.JFormattedTextField fieldIni = null;
        javax.swing.JFormattedTextField fieldFim = null;
        try {
            javax.swing.text.MaskFormatter maskIni = new javax.swing.text.MaskFormatter("##/##/####");
            maskIni.setPlaceholderCharacter('_');
            fieldIni = new javax.swing.JFormattedTextField(maskIni);

            javax.swing.text.MaskFormatter maskFim = new javax.swing.text.MaskFormatter("##/##/####");
            maskFim.setPlaceholderCharacter('_');
            fieldFim = new javax.swing.JFormattedTextField(maskFim);
        } catch (java.text.ParseException e) {
            fieldIni = new javax.swing.JFormattedTextField();
            fieldFim = new javax.swing.JFormattedTextField();
        }

        final javax.swing.JFormattedTextField txtDataInicio = fieldIni;
        final javax.swing.JFormattedTextField txtDataFim = fieldFim;

        javax.swing.JPanel painel = new javax.swing.JPanel(new java.awt.GridLayout(3, 2, 5, 5));
        txtDataInicio.addAncestorListener(new javax.swing.event.AncestorListener() {
            @Override
            public void ancestorAdded(javax.swing.event.AncestorEvent event) {
                javax.swing.SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        txtDataInicio.requestFocusInWindow();
                        txtDataInicio.setCaretPosition(0);
                    }
                });
            }

            @Override
            public void ancestorRemoved(javax.swing.event.AncestorEvent event) {}

            @Override
            public void ancestorMoved(javax.swing.event.AncestorEvent event) {}
        });

        txtDataInicio.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            private void checkAutoTab() {
                String digits = txtDataInicio.getText().replaceAll("[^0-9]", "");
                if (digits.length() == 8) {
                    javax.swing.SwingUtilities.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                            txtDataFim.requestFocusInWindow();
                            txtDataFim.setCaretPosition(0);
                        }
                    });
                }
            }
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) { checkAutoTab(); }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {}
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) { checkAutoTab(); }
        });

        txtDataFim.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                javax.swing.SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        if (txtDataFim.getText().replaceAll("[^0-9]", "").isEmpty()) {
                            txtDataFim.setCaretPosition(0);
                        }
                    }
                });
            }
        });

        java.awt.event.ActionListener submitOnEnter = new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                javax.swing.JComponent comp = (javax.swing.JComponent) e.getSource();
                javax.swing.JOptionPane optionPane = (javax.swing.JOptionPane) javax.swing.SwingUtilities.getAncestorOfClass(javax.swing.JOptionPane.class, comp);
                if (optionPane != null) {
                    optionPane.setValue(javax.swing.JOptionPane.OK_OPTION);
                }
            }
        };
        txtDataInicio.addActionListener(submitOnEnter);
        txtDataFim.addActionListener(submitOnEnter);

        painel.add(new javax.swing.JLabel("Data Início (dd/MM/yyyy):"));
        painel.add(txtDataInicio);
        painel.add(new javax.swing.JLabel("Data Fim (dd/MM/yyyy):"));
        painel.add(txtDataFim);
        painel.add(new javax.swing.JLabel(""));
        painel.add(new javax.swing.JLabel("(Deixe em branco para todas)"));

        int confirma = JOptionPane.showConfirmDialog(null, painel, "Filtro - Relatório de Serviços", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (confirma == JOptionPane.OK_OPTION) {
            try {
                java.text.SimpleDateFormat formatoEntrada = new java.text.SimpleDateFormat("dd/MM/yyyy");
                formatoEntrada.setLenient(false);

                String digitsIni = txtDataInicio.getText().replaceAll("[^0-9]", "");
                String digitsFim = txtDataFim.getText().replaceAll("[^0-9]", "");

                // Construir SQL com filtro de data usando tipos corretos
                String sql = "SELECT OSER.os, data_os, tipo, situacao, equipamento, valor, "
                        + "CLI.nome_cliente, fone_cliente "
                        + "FROM tbos AS OSER "
                        + "INNER JOIN tbclientes AS CLI ON (CLI.id_cliente = OSER.id_cliente) WHERE 1=1";

                java.util.List<java.sql.Date> params = new java.util.ArrayList<>();

                if (!digitsIni.isEmpty()) {
                    if (digitsIni.length() < 8) {
                        JOptionPane.showMessageDialog(null, "Data Início incompleta! Use o formato dd/MM/yyyy");
                        return;
                    }
                    String dataIni = txtDataInicio.getText().trim();
                    java.util.Date dtIni = formatoEntrada.parse(dataIni);
                    sql += " AND data_os >= ?";
                    params.add(new java.sql.Date(dtIni.getTime()));
                }

                if (!digitsFim.isEmpty()) {
                    if (digitsFim.length() < 8) {
                        JOptionPane.showMessageDialog(null, "Data Fim incompleta! Use o formato dd/MM/yyyy");
                        return;
                    }
                    String dataFim = txtDataFim.getText().trim();
                    java.util.Date dtFim = formatoEntrada.parse(dataFim);
                    // Adicionar 1 dia para filtro exclusivo (data_os < dia seguinte)
                    java.util.Calendar cal = java.util.Calendar.getInstance();
                    cal.setTime(dtFim);
                    cal.add(java.util.Calendar.DAY_OF_MONTH, 1);
                    sql += " AND data_os < ?";
                    params.add(new java.sql.Date(cal.getTimeInMillis()));
                }

                sql += " ORDER BY data_os";

                java.sql.PreparedStatement pst = conexao.prepareStatement(sql);
                for (int i = 0; i < params.size(); i++) {
                    pst.setDate(i + 1, params.get(i));
                }
                java.sql.ResultSet rs = pst.executeQuery();

                net.sf.jasperreports.engine.util.JRProperties.setProperty("net.sf.jasperreports.compiler.class", "net.sf.jasperreports.engine.design.JRJavacCompiler");

                File f1 = new File("reports/relatorio_servicos/relatorio_servicos.jasper");
                File f2 = new File("dist/reports/relatorio_servicos/relatorio_servicos.jasper");
                File f3 = new File("C:\\Users\\dario\\JaspersoftWorkspace\\relatorio_servicos\\relatorio_servicos.jasper");

                String jasperPath = null;
                if (f1.exists()) jasperPath = f1.getAbsolutePath();
                else if (f2.exists()) jasperPath = f2.getAbsolutePath();
                else if (f3.exists()) jasperPath = f3.getAbsolutePath();

                if (jasperPath == null || !new File(jasperPath).exists()) {
                    File jrxml = new File("reports/relatorio_servicos/relatorio_servicos.jrxml");
                    if (!jrxml.exists()) {
                        jrxml = new File("C:\\Users\\dario\\JaspersoftWorkspace\\relatorio_servicos\\relatorio_servicos.jrxml");
                    }
                    if (jrxml.exists()) {
                        File targetJasper = new File("reports/relatorio_servicos/relatorio_servicos.jasper");
                        if (!targetJasper.getParentFile().exists()) {
                            targetJasper.getParentFile().mkdirs();
                        }
                        net.sf.jasperreports.engine.JasperCompileManager.compileReportToFile(jrxml.getAbsolutePath(), targetJasper.getAbsolutePath());
                        jasperPath = targetJasper.getAbsolutePath();
                    }
                }

                if (jasperPath != null && new File(jasperPath).exists()) {
                    JasperPrint print = JasperFillManager.fillReport(
                            jasperPath,
                            new HashMap<>(),
                            new net.sf.jasperreports.engine.JRResultSetDataSource(rs));
                    JasperViewer.viewReport(print, false);
                } else {
                    throw new Exception("Arquivo relatorio_servicos.jasper não foi localizado!");
                }
            } catch (java.text.ParseException pe) {
                JOptionPane.showMessageDialog(null, "Data inválida! Use o formato dd/MM/yyyy");
            } catch (Throwable e) {
                e.printStackTrace();
                String msg = "Erro ao gerar relatório:\n" + e.getClass().getName() + "\n" + e.getMessage();
                Throwable causa = e.getCause();
                while (causa != null) {
                    msg += "\n\nCausa: " + causa.getClass().getName() + "\n" + causa.getMessage();
                    causa = causa.getCause();
                }
                JOptionPane.showMessageDialog(null, msg);
            }
        }
    }//GEN-LAST:event_menRelSerActionPerformed


    private void menCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadCliActionPerformed
        TelaCliente cliente = new TelaCliente();
        centralizarInternalFrame(cliente);
        TelaCliente.txtCliPesquisar.requestFocus();

    }//GEN-LAST:event_menCadCliActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Date data = new Date();
        java.text.SimpleDateFormat fData = new java.text.SimpleDateFormat("dd/MM/yyyy");
        java.text.SimpleDateFormat fHora = new java.text.SimpleDateFormat("HH:mm:ss");
        lblData.setText("<html>Data: " + fData.format(data) + "<br>Hora: " + fHora.format(data) + "</html>");
    }//GEN-LAST:event_formWindowActivated


    private void menOpcSaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menOpcSaiActionPerformed
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_menOpcSaiActionPerformed

    private void menAjuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menAjuActionPerformed

    }//GEN-LAST:event_menAjuActionPerformed

    private void menAjuSobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menAjuSobActionPerformed
        TelaSobre sobre = new TelaSobre();
        sobre.setLocationRelativeTo(this);
        sobre.setVisible(true);
    }//GEN-LAST:event_menAjuSobActionPerformed

    private void menCadUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadUsuActionPerformed
        TelaUsuario usuario = new TelaUsuario();
        centralizarInternalFrame(usuario);
        TelaUsuario.txtUsuId.requestFocus();


    }//GEN-LAST:event_menCadUsuActionPerformed

    private void menCadPecaActionPerformed(java.awt.event.ActionEvent evt) {
        TelaPeca peca = new TelaPeca();
        centralizarInternalFrame(peca);
        TelaPeca.txtPecaPesquisar.requestFocus();
    }

    private void menCadUseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadUseActionPerformed

    }//GEN-LAST:event_menCadUseActionPerformed

    private void menRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelActionPerformed

    }//GEN-LAST:event_menRelActionPerformed

    private void menRelCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelCliActionPerformed
        int confirma = JOptionPane.showConfirmDialog(null, "Corfirma a emissão do relatório de clientes?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            try {
                JasperPrint print = JasperFillManager.fillReport("C:\\Users\\dario\\JaspersoftWorkspace\\relatorio_clientes\\relatorio_clientes.jasper", null, conexao);
                JasperViewer.viewReport(print, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_menRelCliActionPerformed

    private void menRelPecasActionPerformed(java.awt.event.ActionEvent evt) {
        TelaRelatorioPecas relPecas = new TelaRelatorioPecas();
        centralizarInternalFrame(relPecas);
    }

    private void menRelOSActionPerformed(java.awt.event.ActionEvent evt) {
        TelaRelatorioOS relOS = new TelaRelatorioOS();
        centralizarInternalFrame(relOS);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblUsuario;
    private javax.swing.JMenu menAju;
    private javax.swing.JMenuItem menAjuSob;
    private javax.swing.JMenuItem menCadCli;
    private javax.swing.JMenuItem menCadOS;
    private javax.swing.JMenu menCadUse;
    public static javax.swing.JMenuItem menCadUsu;
    private javax.swing.JMenuItem menCadPeca;
    private javax.swing.JMenu menOpc;
    private javax.swing.JMenuItem menOpcSai;
    public static javax.swing.JMenu menRel;
    private javax.swing.JMenuItem menRelCli;
    private javax.swing.JMenuItem menRelSer;
    private javax.swing.JMenuItem menRelPecas;
    private javax.swing.JMenuItem menRelOS;
    // End of variables declaration//GEN-END:variables

}
